version: '3.8'

services:

  mariadb:
    image: mariadb:10.6
    restart: always
    container_name: CONTAINER_CINEMA_DB
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: "exit 0"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/cinema_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    container_name: CONTAINER_CINEMA_APP
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  db_data:
